### ISSUE TITLE
Changes in dataset

### ISSUE THREAD

**Issue by doxxitxxyoung** [tttianhao/CLEAN#46]
Hi, thanks to your work, we are also conducting researches on EC-number prediction using dataset you provided in data folder.

However, we've recognized the changes in commit done on Jan, where datasets are changed to older version.

Can you explain about what and why changes are given in dataset from that commit?

Cheers,
Doyeong Hwang

**Comment by canallee** [comment]
Hi, when we constructed the train/test 5-fold split, we randomly split the dataset into 5-fold, and for each test split, we removed the few examples with EC numbers that did not appear in the training data split (since these ECs are impossible to infer). We overlooked this when compiling the full dataset and simply combined the train and test splits for the first fold, leaving some ECs out. This is the initial release of the full datasets (splitxx.csv). 

After we realized this mistake, we changed the full datasets back to the ones that would contain all the EC numbers. However, this would lead to a mismatch of the precomputed distance-matrix, since the number of possible EC numbers was changed. This is the reason behind https://github.com/tttianhao/CLEAN/issues/41. Therefore we reverted to the original full datasets (with missing ECs), where the distance matrix was computed, and the models were trained.

It would be fairly straightforward to recover the full datasets with all the ECs since we released [all the data splits](https://drive.google.com/file/d/1MzYQ--CRK253eAKOmZrD1nzF-mXHfXtq/view). Following issue 41, the results when training on the full datasets with all the ECs are similar to those with incomplete ECs.
